### PR TITLE
Ndje bayi venant boris

### PR DESCRIPTION
**Pull request by ndje-bayi**
Group 17 Q

### CODE REVIEW

**Comment by sas-bergson** [comment]
@ndje-bayi 
Sir 
What's the purpose of all these JSON files?
Do you think it will be efficient to store your words in JSON format?
When the actual analyzer would be looking for a token in your section, it will have to fetch for the actual item using a linear algorithm, making your search algorithm completely inefficient...
Don't you think that you need to design an actual IR that would make your search algorithm more efficient?
Actually, your IR sould be loaded in RAM to make the analyzer faster... JSON will definitely not do the work...
But This is my opinion... I just want to understand your design..
:pensive:

**Review by sas-bergson — COMMENTED** [review]
Your tokenizer is not bad. But a simpler approach would have been to use efficient regular expressions with the appropriate method to split the words.
Look at my own proposal on the main branch

**Review by sas-bergson — COMMENTED** [review]
Your IR is not clear from this design. It is smart to load data from JSON files. But now using dictionnaries to store the data from RAW may not be the smartest approach. These words should be organized in order to reduce the complexity of the search algorithm. 
We definitely want to avoid using a linear search
:sweat:

**Comment by ndje-bayi** [comment]
Good evening Sir!
I agree with you Sir. The linear search algorithm is far from being
efficient... I was just trying to think outside the box... My first
challenge was to enable the analyzer to distinguish the fundamental types
of English words, that is, verbs, nouns, pronouns, adjectives and so on...
so my first thought went to an English dictionary. I mean what source could
be more credible than the English dictionary to tell us what a word is? My
challenge is to find a better dictionary against which the tokenizer will
make references in categorizing the words... My group member just told me
about pydictionary i am going to look into that... for the word
splitting Sir I am going to check your example on the main branch... I just
wanted to go with something simple...

Thank you for your kind remarks Sir they keep me motivated...
Ndje *Bayi Boris*

**Comment by ndje-bayi** [comment]
> @ndje-bayi Sir What's the purpose of all these JSON files? Do you think it will be efficient to store your words in JSON format? When the actual analyzer would be looking for a token in your section, it will have to fetch for the actual item using a linear algorithm, making your search algorithm completely inefficient... Don't you think that you need to design an actual IR that would make your search algorithm more efficient? Actually, your IR sould be loaded in RAM to make the analyzer faster... JSON will definitely not do the work... But This is my opinion... I just want to understand your design.. pensive

**Comment by ndje-bayi** [comment]
> Your tokenizer is not bad. But a simpler approach would have been to use efficient regular expressions with the appropriate method to split the words. Look at my own proposal on the main branch

Hello Sir!
Please Sir look up the regular expression I complied for splitting the words in the tokenizer1_1.py. I think this one is better...

**Pull request closed without merging**
